# Generated by Django 3.1.4 on 2023-05-29 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPredictorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('stock_type', models.CharField(max_length=20)),
                ('predict_type', models.CharField(max_length=20)),
                ('job_path', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PredictHistModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vol_moving_avg', models.BigIntegerField(blank=True, null=True)),
                ('price_rolling_med', models.FloatField(blank=True, null=True)),
                ('price_daily_std', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predict_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predict_hists', to='api.stockpredictormodel')),
            ],
        ),
    ]
